# we can have multiple config files (profiles) as per env.
# --- denotes new config doc in same file
# so currently in this file we have 2 profiles: dev and prod

server:
    error:
        include-message: always
    port: 9002

spring:
   profiles:
       active: dev
---
spring:
    datasource:
        driver-clas-name: com.mysql.jdbc.Driver
        password: vivek
        url: jdbc:mysql://localhost:3306/world  # "world" is the schemaNAme
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
app:
    name: SpringBootTutorial
    welcome:
        message: Welcome to ${app.name} Learning Mr. Vivek in ${spring.profiles.active} Env
    list.values: one,two,three
# adding all api endpoints in actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"